name: Demo Workflow
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  CheckOutRepo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: say complete
        run: |
          echo "completed"
        
    
