name: Workflow Syntax
on:
  push:
    branches:
      - main
    
jobs:
  basics:
    name: "Expressions, Context, Commands"
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.producer_stage.outputs.name }}
    steps:
      - name: Show Contexts
        run: |
          echo "Ref = ${{ github.ref }} "
          echo "Repo = ${{ github.repository }} "
          echo "Actor = ${{ github.actor }} "
          echo "sha = ${{ github.sha }} "

      - name: Workflow Commands
        run: |
          echo "::debug::This is a debug message"
          echo "::warning::This is an warning message"
          echo "::error::This is an error message"
    
      - name: Produce Outputs
        id: producer_stage
        run: |
          echo "name=mugdho" >> $GITHUB_OUTPUT
      
      - name: Show Outputs
        run: |
          echo "My name is ${{ steps.producer_stage.outputs.name }}"

      - name: Environment file
        run: |
          echo "MY_ENV=demo" >> $GITHUB_ENV
      
      - name: Read from Environment file
        run: |
          echo "Env name is MY_ENV = $MY_ENV"

      - name: Job Summary
        run: |
          echo "## Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Actor: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- Ref: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "- Done by: ${{ steps.producer_stage.outputs.name }}" >> $GITHUB_STEP_SUMMARY


  output_passing:
    needs: basics
    name: Output parsing across jobs
    runs-on: ubuntu-latest
    steps:
      - name: Show Previous Stage Output
        run: |
          echo "I said that, my name is ${{ needs.basics.outputs.name }}"
    outputs:
      name: ${{ needs.producer_stage.outputs.name }}