name: Demo Workflow
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup java 21
        uses: actions/setuip-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      
      - name: build jar
        run: |
          ./mvnw clean package
        working-directory: ./app/demo-web-app
        
      - name: end job
        run: echo "Job completed"