name: Demo Workflow
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      
      - name: build jar
        run: |
          ./mvnw clean package
        working-directory: ./app/demo-web-app

      - name: rename jar
        run: mv target/*.jar target/*app.jar
        working-directory: ./app/demo-web-app

      - name: release jar
        uses: softprops/action-gh-release@v2
        with:
          files: ./app/demo-web-app/app.jar
          token: ${{ secrets.TOKEN }}

      - name: end job
        run: echo "Job completed"