name: Workflow Syntax
on:
  push:
    branches:
      - main
    
jobs:
  basics:
    name: "Expressions, Context, Commands"
    runs-on: ubuntu-latest
    steps:
      - name: Show Contexts
        run: |
          echo "Ref = ${{ github.ref }} "
          echo "Repo = ${{ github.repository }} "
          echo "Actor = ${{ github.actor }} "
          echo "sha = ${{ github.sha }} "

      - name: Workflow Commands
        run: |
          echo "::debug::This is a debug message"
          echo "::warning::This is an warning message"
          echo "::error::This is an error message"
    
      - name: Produce Outputs
        id: producer_stage
        run: |
          echo "name=mugdho" >> $GITHUB_OUTPUT
      
      - name: Show Outputs
        run: |
          echo "My name is ${{ steps.producer_stage.outputs.name }}"